[tool.black]
line-length = 79
[tool.poetry]
name = "bank2ynab"
version = "0.1.0"
description = ""
authors = ["bank2ynab"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
requests = "2.20.0"
chardet = ">=3.0.2"
pandas = ">=1.3.4"
pdfplumber = ">=0.6.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.isort]
profile = "black"
