from _typeshed import Incomplete
from bank2ynab.ynab_api_response import YNABError as YNABError

class APIInterface:
    budget_info: Incomplete
    logger: Incomplete
    api_token: Incomplete
    def __init__(self, api_token: str) -> None: ...
    def access_api(self, *, budget_id: str, keyword: str, method: str, data: dict) -> dict: ...
    def api_read(self, *, budget_id: str, keyword: str) -> dict: ...
    def post_transactions(self, *, budget_id: str, data: dict) -> None: ...
    def get_budget_accounts(self, *, budget_id: str) -> dict[str, dict]: ...
    def get_budgets(self) -> dict[str, dict]: ...
    @staticmethod
    def fix_id_based_dicts(input_data: dict) -> dict[str, dict]: ...
