from _typeshed import Incomplete
from typing import Any

class ConfigHandler:
    logger: Incomplete
    bank_conf_path: Incomplete
    user_conf_path: Incomplete
    config: Incomplete
    user_config: Incomplete
    def __init__(self) -> None: ...
    def save_account_selection(self, bank, budget_id, account_id) -> None: ...
    def fix_conf_params(self, section: str) -> dict[str, Any]: ...
    def get_config_line_str(self, section_name: str, param: str) -> str: ...
    def get_config_line_int(self, section_name: str, param: str) -> int: ...
    def get_config_line_flt(self, section_name: str, param: str) -> float: ...
    def get_config_line_boo(self, section_name: str, param: str) -> bool: ...
    def get_config_line_lst(self, section_name: str, param: str, splitter: str) -> list[Any]: ...
