from pathlib import Path
from typing import List

def get_files(name: str, file_pattern: str, try_path: str, regex_active: bool, ext: str, prefix: str) -> List[str]: ...
def find_directory(filepath: str) -> Path: ...
def detect_encoding(filepath: str) -> str: ...
