from _typeshed import Incomplete

logger: Incomplete

def get_user_input(options: list, msg: str) -> str: ...
def display_options(options: list): ...
def get_int_input(min_val: int, max_val: int, msg: str) -> int: ...
