from _typeshed import Incomplete

class YNABClient:
    API_ENDPOINT: str
    API_VERSION: str
    auth_token: Incomplete
    client: Incomplete
    base_uri: Incomplete
    def __init__(self, *, api_token: str) -> None: ...
    def list_budgets(self) -> dict: ...
    def get_budget(self, budget_id: str) -> dict: ...
    def list_accounts(self, budget_id: str) -> dict: ...
    def get_account(self, budget_id: str, account_id: str) -> dict: ...
