from bank2ynab.bank_handler import BankHandler as BankHandler
from typing import Optional

class NullBank(BankHandler):
    name: str
    def __init__(self, config_dict: dict) -> None: ...
    def read_data(self, file_path: Optional[str] = ...): ...
    def get_files(self): ...
    def write_data(self, source_file_path, data) -> None: ...

def build_bank(config): ...
