from bank_process import B2YBank

class RaiffeisenRCMPlugin(B2YBank):
    name: str
    def __init__(self, config_object) -> None: ...
    def read_data(self, file_path): ...

def build_bank(config): ...
